# Generated by Django 6.0.4 on 2026-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_adminprofile_employee_order_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images/products/'),
        ),
    ]
