# Generated by Django 6.0.4 on 2026-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('supports_takeaway', models.BooleanField(default=False)),
                ('supports_dine_in', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='screenonboarding',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='screen_onboarding/'),
        ),
    ]
