# Generated by Django 6.0.4 on 2026-06-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_store_alter_screenonboarding_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
    ]
