# Generated by Django 6.0.4 on 2026-06-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_remove_store_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_increment', models.FloatField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('recommend', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customization_blocks',
            },
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('nutrition', models.JSONField(blank=True, null=True)),
                ('steps_to_burn', models.IntegerField(blank=True, null=True)),
                ('reward_stars_required', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customization_options',
            },
        ),
        migrations.CreateModel(
            name='StoreOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'store_operating_hours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_categories/')),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='adminside_c_slug_59f72f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='adminside_p_categor_c7cb86_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='adminside_p_product_c3e387_idx',
        ),
        migrations.RemoveField(
            model_name='store',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='store',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='admin',
            name='country_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='app_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_catering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reward_stars_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='steps_to_burn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warning_label',
            field=models.CharField(default='⚠️ Please Order 48 hours in advance', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
        migrations.AddField(
            model_name='store',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='stores', to='adminside.amenity'),
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='adminside.product'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='block',
            field=models.ForeignKey(blank=True, db_column='block_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='adminside.customization'),
        ),
        migrations.AddField(
            model_name='storeoperatinghour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='adminside.store'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='adminside.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='adminside.subcategory'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_on_way',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddConstraint(
            model_name='storeoperatinghour',
            constraint=models.UniqueConstraint(fields=('store', 'day'), name='unique_store_day'),
        ),
    ]
