# Generated by Django 6.0.4 on 2026-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_product_opening_stock_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='product',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_on_way',
            field=models.IntegerField(default=0),
        ),
    ]
