# Generated by Django 6.0.4 on 2026-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_on_way',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
