# Generated by Django 6.0.4 on 2026-06-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_product_quantity_alter_product_opening_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
