# Generated by Django 6.0.4 on 2026-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_delete_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenonboarding',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddConstraint(
            model_name='screenonboarding',
            constraint=models.UniqueConstraint(fields=('sort_order',), name='unique_screenonboarding_sort_order'),
        ),
    ]
