# Generated by Django 6.0.4 on 2026-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0019_alter_screenonboarding_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenonboarding',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='screenonboarding',
            name='unique_screenonboarding_sort_order',
        ),
        migrations.RemoveIndex(
            model_name='screenonboarding',
            name='adminside_s_is_acti_6d5456_idx',
        ),
        migrations.RenameField(
            model_name='screenonboarding',
            old_name='sort_order',
            new_name='display_order',
        ),
        migrations.AddIndex(
            model_name='screenonboarding',
            index=models.Index(fields=['is_active', 'display_order'], name='adminside_s_is_acti_dd0b0a_idx'),
        ),
    ]
