# Generated by Django 6.0.4 on 2026-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_alter_screenonboarding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenonboarding',
            name='display_order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
