# Generated by Django 6.0.4 on 2026-06-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0013_amenity_customization_customizationoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTPVerification',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('otp_code', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('display_order_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('master_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('order_status', models.CharField(default='PENDING', max_length=255)),
                ('dynamic_eta', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(default='TAKEAWAY', max_length=255)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_date_time', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(blank=True, max_length=255, null=True)),
                ('grand_total', models.FloatField(default=0.0)),
                ('previous_payment', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='PAID', max_length=255)),
                ('is_editing', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0.0)),
                ('points_status', models.CharField(default='PENDING', max_length=255)),
                ('points_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, db_column='store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.store')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('base_price', models.FloatField(default=0.0)),
                ('type1_total', models.FloatField(default=0.0)),
                ('type2_total', models.FloatField(default=0.0)),
                ('unit_final_price', models.FloatField(default=0.0)),
                ('row_total', models.FloatField(default=0.0)),
                ('is_reward_applied', models.BooleanField(default=False)),
                ('points_used', models.IntegerField(default=0)),
                ('reward_badge', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='userside.order')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('country_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_source', models.CharField(blank=True, max_length=255, null=True)),
                ('temporary_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email_marketing_opt_in', models.BooleanField(default=True)),
                ('personalization_opt_in', models.BooleanField(default=True)),
                ('royale_points_balance', models.FloatField(default=0.0)),
                ('annual_status_tracker', models.FloatField(default=0.0)),
                ('tier_status', models.CharField(default='Standard', max_length=255)),
                ('show_gold_unlock_popup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_store', models.ForeignKey(blank=True, db_column='selected_store_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.store')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.user'),
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('platform', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
            options={
                'db_table': 'user_device_tokens',
            },
        ),
    ]
